---
name: DockerDeploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Build Docker
      shell: bash
      run: |
        docker build -t ${{ github.repository }}:${{ github.sha }} .
        docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:${{ github.event.inputs.branch }}
        docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}

    - name: Push Docker
      shell: bash

      run: |
        docker push ${{ github.repository }}:${{ github.event.inputs.branch }}
        docker push ${{ github.repository }}:latest
