---
name: DockerDeploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}

    - name: Build and Push Docker to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          crashserver/${{ github.repository }}:${{ github.event.inputs.branch }}
          crashserver/${{ github.repository }}:latest
          
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker to Github Packages
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/crashserver/${{ github.repository }}:${{ github.event.inputs.branch }}
          ghcr.io/crashserver/${{ github.repository }}:latest
